# Generated by Django 4.0.5 on 2023-06-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
