# Generated by Django 4.0.5 on 2023-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_city_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='y',
            field=models.FloatField(),
        ),
    ]
